# KNP Paginator Bundle Configuration
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField # filter field query parameter name
        filter_value_name: filterValue # filter value query paameter name
    template:
        pagination: blocks/pagination.html.twig                     # sliding pagination controls template
        sortable: blocks/sortable.html.twig                         # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'     # filters template
