parameters:
    ##
    # Core Config
    ##
    app.active_language: [ en, tr ]
    app.user_registration: true
    app.user_default_group: null
    app.user_login_redirect: admin.dashboard
    app.user_logout_redirect: security_login
    app.user_email_confirmation: true
    app.user_welcome_email: true

    ##
    # General Default Config
    ##
    app.head_title: 'pdAdmin'
    app.head_title_pattern: '&T - &P'
    app.head_description: ''
    app.head_author: 'pdAdmin'
    app.head_keywords: 'pdAdmin, opensource'
    app.footer_copyright: 'pdAdmin Developed with Symfony 5'
    app.default_locale: 'tr'
    app.list_count: 30
    app.site_logo: 'default/logo.png'
    app.site_favicon: 'default/favicon.ico'

    ##
    # Media Default Config
    ##
    app.media_optimize: true
    app.media_max_width: 1028
    app.media_max_height: 768
    app.media_quality: 75

    ##
    # API
    ##
    api.route: ^/api
